In [47]:
import pandas as pd

In [48]:
movies_df = pd.read_csv('../../datasets/movies.csv')
movies_df.columns = movies_df.columns.str.lower()
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movies    9999 non-null   object
 1   year      9355 non-null   object
 2   genre     9919 non-null   object
 3   rating    8179 non-null   float64
 4   one-line  9999 non-null   object
 5   stars     9999 non-null   object
 6   votes     8179 non-null   object
 7   runtime   7041 non-null   float64
 8   gross     460 non-null    object
dtypes: float64(2), object(7)
memory usage: 703.2+ KB

In [49]:
movies_df.head()

,movies,year,genre,rating,one-line,stars,votes,runtime,gross
0,Blood Red Sky,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0,NaN
1,Masters of the Universe: Revelation,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0,NaN
2,The Walking Dead,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0,NaN
3,Rick and Morty,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0,NaN
4,Army of Thieves,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN,NaN

In [50]:
movies_df.isna().mean() * 100

movies       0.000000
year         6.440644
genre        0.800080
rating      18.201820
one-line     0.000000
stars        0.000000
votes       18.201820
runtime     29.582958
gross       95.399540
dtype: float64

In [51]:
movies_df = movies_df.drop(columns=['gross', 'movies'])
movies_df.head()

,year,genre,rating,one-line,stars,votes,runtime
0,(2021),"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0
1,(2021– ),"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0
2,(2010–2022),"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0
3,(2013– ),"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0
4,(2021),"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN

In [52]:
movies_df['year'] = movies_df['year'].str.extract(r'(\d{4})').astype(float)
movies_df.head()

,year,genre,rating,one-line,stars,votes,runtime
0,2021.0,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,\n Director:\nPeter Thorwarth\n| \n Star...,"21,062",121.0
1,2021.0,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"\n \n Stars:\nChris Wood, \nSara...","17,870",25.0
2,2010.0,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"\n \n Stars:\nAndrew Lincoln, \n...","885,805",44.0
3,2013.0,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"\n \n Stars:\nJustin Roiland, \n...","414,849",23.0
4,2021.0,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",\n Director:\nMatthias Schweighöfer\n| \n ...,NaN,NaN

In [53]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   year      9251 non-null   float64
 1   genre     9919 non-null   object
 2   rating    8179 non-null   float64
 3   one-line  9999 non-null   object
 4   stars     9999 non-null   object
 5   votes     8179 non-null   object
 6   runtime   7041 non-null   float64
dtypes: float64(3), object(4)
memory usage: 546.9+ KB

In [54]:
movies_df['has_director'] = movies_df['stars'].str.lower().str.contains('director:').astype(int)
movies_df['has_stars'] = movies_df['stars'].str.lower().str.contains('stars:').astype(int)

movies_df = movies_df.drop(columns=['stars'])

movies_df.head()

,year,genre,rating,one-line,votes,runtime,has_director,has_stars
0,2021.0,"\nAction, Horror, Thriller",6.1,\nA woman with a mysterious illness is forced ...,"21,062",121.0,1,1
1,2021.0,"\nAnimation, Action, Adventure",5.0,\nThe war for Eternia begins again in what may...,"17,870",25.0,0,1
2,2010.0,"\nDrama, Horror, Thriller",8.2,\nSheriff Deputy Rick Grimes wakes up from a c...,"885,805",44.0,0,1
3,2013.0,"\nAnimation, Adventure, Comedy",9.2,\nAn animated series that follows the exploits...,"414,849",23.0,0,1
4,2021.0,"\nAction, Crime, Horror",NaN,"\nA prequel, set before the events of Army of ...",NaN,NaN,1,1

In [55]:
movies_df['votes'] = movies_df['votes'].str.replace(',', '').astype(float)

In [56]:
from sklearn.preprocessing import MultiLabelBinarizer

movies_df['genre_list']  = (
    movies_df['genre']
    .fillna('')
    .str.lower()
    .replace('\n', '', regex=False)
    .str.strip()
    .apply(lambda s: [g.strip() for g in s.split(',')] if s else [])
)

mlb = MultiLabelBinarizer()

genre_encoded = pd.DataFrame(
    mlb.fit_transform(movies_df['genre_list']),
    columns = mlb.classes_,
    index = movies_df.index
)

# genre_encoded.head()

movies_df = pd.concat([movies_df, genre_encoded], axis=1)

movies_df['one-line'] = (
    movies_df['one-line']
    .fillna('')
    .str.lower()
    .str.replace('\n', '', regex=False)
    .str.strip()
)

movies_df = movies_df.drop(columns=['genre', 'genre_list', 'one-line'])





movies_df.head()

,year,rating,votes,runtime,has_director,has_stars,action,adventure,animation,biography,...,news,reality-tv,romance,sci-fi,short,sport,talk-show,thriller,war,western
0,2021.0,6.1,21062.0,121.0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,2021.0,5.0,17870.0,25.0,0,1,1,1,1,0,...,0,0,0,0,0,0,0,0,0,0
2,2010.0,8.2,885805.0,44.0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,2013.0,9.2,414849.0,23.0,0,1,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
4,2021.0,NaN,NaN,NaN,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [57]:
# Feature Engineering
movies_df['director_and_stars'] = ((movies_df['has_stars'] == 1) & (movies_df['has_director'] == 1)).astype(int)
movies_df['released_in_2000s'] = (movies_df['year'] >= 2000).astype(int)
movies_df['modern_with_credits'] = ((movies_df['released_in_2000s'] == 1) & (movies_df['director_and_stars'] == 1)).astype(int)


movies_df['is_short_movie'] = (movies_df['runtime'] <= 90).astype(int)
movies_df['short_horror'] = ((movies_df['horror'] == 1) & (movies_df['is_short_movie'] == 1)).astype(int)
movies_df['short_documentary'] = ((movies_df['documentary'] == 1) & (movies_df['is_short_movie'] == 1)).astype(int)


movies_df['runtime_percentile'] = movies_df['runtime'].rank(pct=True)

movies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9999 entries, 0 to 9998
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   year                 9251 non-null   float64
 1   rating               8179 non-null   float64
 2   votes                8179 non-null   float64
 3   runtime              7041 non-null   float64
 4   has_director         9999 non-null   int64
 5   has_stars            9999 non-null   int64
 6   action               9999 non-null   int64
 7   adventure            9999 non-null   int64
 8   animation            9999 non-null   int64
 9   biography            9999 non-null   int64
 10  comedy               9999 non-null   int64
 11  crime                9999 non-null   int64
 12  documentary          9999 non-null   int64
 13  drama                9999 non-null   int64
 14  family               9999 non-null   int64
 15  fantasy              9999 non-null   int64
 16  film-noir            9999 non-null   int64
 17  game-show            9999 non-null   int64
 18  history              9999 non-null   int64
 19  horror               9999 non-null   int64
 20  music                9999 non-null   int64
 21  musical              9999 non-null   int64
 22  mystery              9999 non-null   int64
 23  news                 9999 non-null   int64
 24  reality-tv           9999 non-null   int64
 25  romance              9999 non-null   int64
 26  sci-fi               9999 non-null   int64
 27  short                9999 non-null   int64
 28  sport                9999 non-null   int64
 29  talk-show            9999 non-null   int64
 30  thriller             9999 non-null   int64
 31  war                  9999 non-null   int64
 32  western              9999 non-null   int64
 33  director_and_stars   9999 non-null   int64
 34  released_in_2000s    9999 non-null   int64
 35  modern_with_credits  9999 non-null   int64
 36  is_short_movie       9999 non-null   int64
 37  short_horror         9999 non-null   int64
 38  short_documentary    9999 non-null   int64
 39  runtime_percentile   7041 non-null   float64
dtypes: float64(5), int64(35)
memory usage: 3.1 MB

In [58]:
movies_df.head()

,year,rating,votes,runtime,has_director,has_stars,action,adventure,animation,biography,...,thriller,war,western,director_and_stars,released_in_2000s,modern_with_credits,is_short_movie,short_horror,short_documentary,runtime_percentile
0,2021.0,6.1,21062.0,121.0,1,1,1,0,0,0,...,1,0,0,1,1,1,0,0,0,0.934242
1,2021.0,5.0,17870.0,25.0,0,1,1,1,1,0,...,0,0,0,0,1,0,1,0,0,0.151044
2,2010.0,8.2,885805.0,44.0,0,1,0,0,0,0,...,1,0,0,0,1,0,1,1,0,0.332907
3,2013.0,9.2,414849.0,23.0,0,1,0,1,1,0,...,0,0,0,0,1,0,1,0,0,0.074989
4,2021.0,NaN,NaN,NaN,1,1,1,0,0,0,...,0,0,0,1,1,1,0,0,0,NaN

In [59]:
# Model Ridge
from sklearn.metrics import r2_score, root_mean_squared_error, mean_absolute_error, mean_squared_error
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import Ridge
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor

movies_model = movies_df.dropna(subset=['year', 'rating']).copy()



X = movies_model.drop(columns=['rating'])
y = movies_model['rating']



X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


def linear_model(model):
    return (
        Pipeline([
            ('impute', SimpleImputer()),
            ('scaler', StandardScaler()),
            ('model', model)
        ])
    )

movies_model.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8179 entries, 0 to 9979
Data columns (total 40 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   year                 8179 non-null   float64
 1   rating               8179 non-null   float64
 2   votes                8179 non-null   float64
 3   runtime              6786 non-null   float64
 4   has_director         8179 non-null   int64
 5   has_stars            8179 non-null   int64
 6   action               8179 non-null   int64
 7   adventure            8179 non-null   int64
 8   animation            8179 non-null   int64
 9   biography            8179 non-null   int64
 10  comedy               8179 non-null   int64
 11  crime                8179 non-null   int64
 12  documentary          8179 non-null   int64
 13  drama                8179 non-null   int64
 14  family               8179 non-null   int64
 15  fantasy              8179 non-null   int64
 16  film-noir            8179 non-null   int64
 17  game-show            8179 non-null   int64
 18  history              8179 non-null   int64
 19  horror               8179 non-null   int64
 20  music                8179 non-null   int64
 21  musical              8179 non-null   int64
 22  mystery              8179 non-null   int64
 23  news                 8179 non-null   int64
 24  reality-tv           8179 non-null   int64
 25  romance              8179 non-null   int64
 26  sci-fi               8179 non-null   int64
 27  short                8179 non-null   int64
 28  sport                8179 non-null   int64
 29  talk-show            8179 non-null   int64
 30  thriller             8179 non-null   int64
 31  war                  8179 non-null   int64
 32  western              8179 non-null   int64
 33  director_and_stars   8179 non-null   int64
 34  released_in_2000s    8179 non-null   int64
 35  modern_with_credits  8179 non-null   int64
 36  is_short_movie       8179 non-null   int64
 37  short_horror         8179 non-null   int64
 38  short_documentary    8179 non-null   int64
 39  runtime_percentile   6786 non-null   float64
dtypes: float64(5), int64(35)
memory usage: 2.6 MB

In [60]:

ridge_pipeline = linear_model(Ridge(alpha=1.0))
ridge_pipeline.fit(X_train, y_train)
y_pred = ridge_pipeline.predict(X_test)

def regression_model_metrics(y_test, y_pred):
    return {
        "R2": r2_score(y_test, y_pred),
        "RMSE": root_mean_squared_error(y_test, y_pred),
        "MAE": mean_absolute_error(y_test, y_pred),
        "MSE": mean_squared_error(y_test, y_pred)
    }

regression_model_metrics(y_test, y_pred)

{'R2': 0.26271497910318276,
 'RMSE': 1.0541637702288247,
 'MAE': 0.8215564109276212,
 'MSE': 1.1112612544630502}

In [61]:
def tree_model(model):
    return (
        Pipeline([
            ('impute', SimpleImputer()),
            ('model', model)
        ])
    )

xg_pipeline = tree_model(XGBRegressor())
xg_pipeline.fit(X_train, y_train)
xg_pred = xg_pipeline.predict(X_test)

regression_model_metrics(y_test, xg_pred)

{'R2': 0.5077031819071343,
 'RMSE': 0.8613980717719346,
 'MAE': 0.6329191710371843,
 'MSE': 0.7420066380524071}

In [62]:
import pandas as pd

xgb_model = xg_pipeline.named_steps['model']

importance = pd.Series(
    xgb_model.feature_importances_,
    index=X_train.columns
).sort_values(ascending=False)

importance

modern_with_credits    0.120627
documentary            0.106952
horror                 0.075277
drama                  0.053333
runtime                0.044148
sci-fi                 0.036809
runtime_percentile     0.033471
animation              0.033106
sport                  0.032562
action                 0.030060
reality-tv             0.029423
adventure              0.027030
fantasy                0.026662
musical                0.025416
thriller               0.023585
history                0.021489
short                  0.020850
director_and_stars     0.020607
game-show              0.020159
romance                0.019367
is_short_movie         0.019346
votes                  0.019264
has_stars              0.018242
family                 0.017323
has_director           0.014123
talk-show              0.012362
mystery                0.012017
comedy                 0.011671
crime                  0.010974
year                   0.010101
music                  0.010063
short_documentary      0.009700
short_horror           0.009596
war                    0.007794
biography              0.007680
news                   0.005194
western                0.002365
film-noir              0.001250
released_in_2000s      0.000000
dtype: float32